// --- MOCK DATABASE & STORE INFO ---
const storeInfo = {
  name: "CashShilpo Flagship",
  logoUrl: "https://placehold.co/100x100/007BFF/FFFFFF?text=CS",
  address: "123 Commerce St, Business City, 12345",
  contact: "555-0101",
  website: "cashshilpo.com",
  taxId: "BIN-123456789",
  socials: "@cashshilpo",
  baseCurrency: "USD",
  defaultDisplayCurrency: "BDT", // New: Default for the store
  currencies: {
    USD: { name: "US Dollar", symbol: "$", rate: 1 },
    BDT: { name: "Bangladeshi Taka", symbol: "৳", rate: 117.5 },
    EUR: { name: "Euro", symbol: "€", rate: 0.92 },
    GBP: { name: "British Pound", symbol: "£", rate: 0.79 },
    JPY: { name: "Japanese Yen", symbol: "¥", rate: 157.25 },
    INR: { name: "Indian Rupee", symbol: "₹", rate: 83.5 },
  },
};

let mockDB = {
  unitsOfMeasurement: [
    { id: "pcs", name: "Piece(s)", allowsDecimal: false },
    { id: "kg", name: "Kilogram", allowsDecimal: true },
    { id: "g", name: "Gram", allowsDecimal: true },
    { id: "ltr", name: "Liter", allowsDecimal: true },
    { id: "ml", name: "Milliliter", allowsDecimal: true },
    { id: "box", name: "Box", allowsDecimal: false },
    { id: "pack", name: "Pack", allowsDecimal: false },
  ],
  products: [
    // Standard Item
    {
      id: "SKU001",
      name: "Espresso Coffee Beans",
      productType: "physical",
      category: "Coffee",
      costPrice: 9.5,
      price: 15.99,
      stock: 45,
      sales: 120,
      uomId: "pcs",
      taxable: true,
      customData: { Brand: "Kafé", Roast: "Dark" },
    },
    // Weighted Item
    {
      id: "SKU002",
      name: "Organic Apples",
      productType: "physical",
      category: "Produce",
      costPrice: 1.5,
      price: 2.99,
      stock: 85,
      sales: 95,
      uomId: "kg",
      taxable: true,
      customData: { Variety: "Gala" },
    },
    // Service Item
    {
      id: "SVC001",
      name: "Smartphone Screen Repair",
      productType: "service",
      category: "Services",
      costPrice: 25.0,
      price: 79.99,
      stock: Infinity,
      sales: 15,
      uomId: "pcs",
      taxable: false,
      customData: { "Turnaround Time": "24 Hours" },
    },
    // Perishable/Batched Item (Medicine)
    {
      id: "MED500",
      name: "Paracetamol 500mg",
      productType: "physical",
      category: "Medicine",
      costPrice: 2.0,
      price: 4.99,
      stock: 100,
      sales: 50,
      uomId: "box",
      taxable: false,
      hasExpiry: true,
      batches: [
        { batchId: "B101", expiryDate: "2026-12-31", stock: 60 },
        { batchId: "B102", expiryDate: "2027-06-30", stock: 40 },
      ],
      customData: {
        Manufacturer: "PharmaCo",
        "Generic Name": "Acetaminophen",
        Strength: "500mg",
      },
    },
    // Serialized Item
    {
      id: "ELEC01",
      name: "Hyperion X1 Smartphone",
      productType: "physical",
      category: "Electronics",
      costPrice: 450.0,
      price: 699.99,
      stock: 5,
      sales: 2,
      uomId: "pcs",
      taxable: true,
      isSerialized: true,
      serials: [
        "SN-HX1-00A1",
        "SN-HX1-00A2",
        "SN-HX1-00A3",
        "SN-HX1-00A4",
        "SN-HX1-00A5",
      ],
      customData: {
        Brand: "Hyperion",
        Model: "X1",
        Specifications: "128GB Storage, 8GB RAM",
      },
    },
    // Parent Product for Variants
    {
      id: "TSHIRT01",
      name: "CashShilpo Logo T-Shirt",
      productType: "physical",
      category: "Apparel",
      costPrice: 8.0,
      price: 19.99,
      stock: 0,
      sales: 0,
      uomId: "pcs",
      taxable: true,
      hasVariants: true,
      customData: {},
    },
    // Variant Children
    {
      id: "TSHIRT01-S-BLK",
      name: "CashShilpo Logo T-Shirt (S, Black)",
      parentSKU: "TSHIRT01",
      productType: "physical",
      category: "Apparel",
      costPrice: 8.0,
      price: 19.99,
      stock: 20,
      sales: 12,
      uomId: "pcs",
      taxable: true,
      variantInfo: { Size: "S", Color: "Black" },
      customData: { Material: "100% Cotton" },
    },
    {
      id: "TSHIRT01-M-BLK",
      name: "CashShilpo Logo T-Shirt (M, Black)",
      parentSKU: "TSHIRT01",
      productType: "physical",
      category: "Apparel",
      costPrice: 8.0,
      price: 19.99,
      stock: 30,
      sales: 25,
      uomId: "pcs",
      taxable: true,
      variantInfo: { Size: "M", Color: "Black" },
      customData: { Material: "100% Cotton" },
    },
    {
      id: "TSHIRT01-M-WHT",
      name: "CashShilpo Logo T-Shirt (M, White)",
      parentSKU: "TSHIRT01",
      productType: "physical",
      category: "Apparel",
      costPrice: 8.0,
      price: 19.99,
      stock: 25,
      sales: 18,
      uomId: "pcs",
      taxable: true,
      variantInfo: { Size: "M", Color: "White" },
      customData: { Material: "100% Cotton" },
    },
  ],
  customers: [
    {
      id: "CUST001",
      name: "John Doe",
      phone: "555-1234",
      email: "john.doe@email.com",
      loyaltyPoints: 150,
      joinDate: "2025-01-15",
      address: "456 Oak Avenue",
      loyaltyId: "CS-JD-456",
    },
    {
      id: "CUST002",
      name: "Jane Smith",
      phone: "555-5678",
      email: "jane.smith@email.com",
      loyaltyPoints: 275,
      joinDate: "2024-11-22",
      address: "789 Pine Street",
      loyaltyId: "CS-JS-789",
    },
    {
      id: "CUST003",
      name: "Michael Brown",
      phone: "555-8765",
      email: "michael.b@email.com",
      loyaltyPoints: 80,
      joinDate: "2025-05-10",
      address: "101 Maple Lane",
      loyaltyId: "CS-MB-101",
    },
  ],
  invoices: [
    {
      id: "INV001",
      customerId: "CUST001",
      customerName: "John Doe",
      total: 19.98,
      status: "Paid",
      date: "2025-09-08",
      items: [
        {
          id: "SKU001",
          name: "Espresso Coffee Beans",
          productType: "physical",
          category: "Coffee",
          costPrice: 9.5,
          price: 15.99,
          stock: 45,
          sales: 120,
          uomId: "pcs",
          taxable: true,
          qty: 1,
        },
      ],
      cashier: "Alice",
      storeId: "STR-01",
      currency: "USD",
      exchangeRate: 1,
      totalInBaseCurrency: 19.98,
    },
    {
      id: "INV002",
      customerId: "CUST002",
      customerName: "Jane Smith",
      total: 8.97,
      status: "Pending",
      date: "2025-09-07",
      items: [
        {
          id: "SKU002",
          name: "Organic Apples",
          productType: "physical",
          category: "Produce",
          costPrice: 1.5,
          price: 2.99,
          stock: 85,
          sales: 95,
          uomId: "kg",
          taxable: true,
          qty: 3,
        },
      ],
      cashier: "Bob",
      storeId: "STR-01",
      currency: "USD",
      exchangeRate: 1,
      totalInBaseCurrency: 8.97,
    },
    {
      id: "INV003",
      customerId: "CUST003",
      customerName: "Michael Brown",
      total: 699.99,
      status: "Paid",
      date: "2025-09-05",
      items: [
        {
          id: "ELEC01",
          name: "Hyperion X1 Smartphone",
          productType: "physical",
          category: "Electronics",
          costPrice: 450.0,
          price: 699.99,
          stock: 5,
          sales: 2,
          uomId: "pcs",
          taxable: true,
          isSerialized: true,
          serials: [
            "SN-HX1-00A1",
            "SN-HX1-00A2",
            "SN-HX1-00A3",
            "SN-HX1-00A4",
            "SN-HX1-00A5",
          ],
          qty: 1,
          serialNumber: "SN-HX1-00A6",
        },
      ],
      cashier: "Alice",
      storeId: "STR-01",
      currency: "USD",
      exchangeRate: 1,
      totalInBaseCurrency: 699.99,
    },
  ],
  employees: [
    {
      id: "EMP01",
      name: "Admin User",
      pin: "1234",
      role: "Admin",
      avatarUrl: "https://placehold.co/40x40/007BFF/ffffff?text=A",
    },
    {
      id: "EMP02",
      name: "Manager Mike",
      pin: "1111",
      role: "Manager",
      avatarUrl: "https://placehold.co/40x40/28a745/ffffff?text=M",
    },
    {
      id: "EMP03",
      name: "Cashier Chloe",
      pin: "0000",
      role: "Cashier",
      avatarUrl: "https://placehold.co/40x40/ffc107/ffffff?text=C",
    },
  ],
  notifications: [
    {
      id: 1,
      type: "stock",
      message: "Organic Apples are low on stock (15 remaining).",
      read: false,
      date: "2025-09-10",
    },
    {
      id: 2,
      type: "info",
      message: "System update scheduled for tonight at 2 AM.",
      read: false,
      date: "2025-09-10",
    },
    {
      id: 3,
      type: "sale",
      message: "New sale record: INV003 for $699.99.",
      read: true,
      date: "2025-09-05",
    },
  ],
};

// --- SMART SYSTEM PROFILES ---
let businessProfiles = {
  general: {
    name: "General Store",
    icon: "store",
    terminology: {
      product: "Product",
      inventory: "Inventory",
      category: "Category",
    },
    features: { serials: true, expiry: true, service: true },
    customFields: [
      { name: "brand", label: "Brand", type: "text" },
      { name: "supplier", label: "Supplier", type: "text" },
    ],
  },
  grocery: {
    name: "Super Shop",
    icon: "shopping-cart",
    terminology: {
      product: "Item",
      inventory: "Stock",
      category: "Department",
    },
    features: { serials: false, expiry: true, service: false },
    customFields: [
      { name: "brand", label: "Brand", type: "text" },
      {
        name: "weight",
        label: "Net Weight",
        type: "text",
        placeholder: "e.g., 500g, 1L",
      },
    ],
  },
  electronics: {
    name: "Electronics Store",
    icon: "smartphone",
    terminology: {
      product: "Device",
      inventory: "Inventory",
      category: "Brand",
    },
    features: { serials: true, expiry: false, service: true },
    customFields: [
      { name: "brand", label: "Brand", type: "text" },
      { name: "model", label: "Model", type: "text" },
      { name: "specifications", label: "Specifications", type: "textarea" },
    ],
  },
  pharmacy: {
    name: "Pharmacy",
    icon: "first-aid-kit",
    terminology: {
      product: "Medicine",
      inventory: "Stock",
      category: "Category",
    },
    features: { serials: false, expiry: true, service: false },
    customFields: [
      { name: "manufacturer", label: "Manufacturer", type: "text" },
      { name: "genericName", label: "Generic Name", type: "text" },
      {
        name: "strength",
        label: "Strength",
        type: "text",
        placeholder: "e.g., 500mg",
      },
    ],
  },
  restaurant: {
    name: "Restaurant",
    icon: "utensils-crossed",
    terminology: {
      product: "Dish",
      inventory: "Ingredients",
      category: "Menu Section",
    },
    features: { serials: false, expiry: false, service: true },
    customFields: [
      { name: "ingredients", label: "Key Ingredients", type: "textarea" },
      {
        name: "spiceLevel",
        label: "Spice Level",
        type: "select",
        options: ["Mild", "Medium", "Hot", "Extra Hot"],
      },
      { name: "isVeg", label: "Vegetarian", type: "checkbox" },
    ],
  },
  apparel: {
    name: "Apparel Boutique",
    icon: "shirt",
    terminology: {
      product: "Apparel",
      inventory: "Stock",
      category: "Collection",
    },
    features: { serials: false, expiry: false, service: false },
    customFields: [
      { name: "color", label: "Color", type: "text" },
      {
        name: "size",
        label: "Size",
        type: "select",
        options: ["XS", "S", "M", "L", "XL", "XXL"],
      },
      { name: "material", label: "Material", type: "text" },
    ],
  },
};

// --- APPLICATION STATE ---
let appState = {
  tabs: [],
  activeTabId: null,
  isSidebarCollapsed: false,
  currentUser: null, // Will hold the logged-in employee object
  currentCurrency: storeInfo.defaultDisplayCurrency || storeInfo.baseCurrency,
  settings: {
    selectedReceiptTemplate: "modern",
    businessType: "general",
    defaultCurrency: storeInfo.defaultDisplayCurrency || storeInfo.baseCurrency,
  },
  customProfiles: {}, // New: Stores custom business profiles
  session: {
    storeId: "STR-01",
  },
};
let posState = { sales: [], activeSaleId: null, saleCounter: 1 };
